package com.nortal.clark.training.assignment.model;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.io.Serializable;

@AllArgsConstructor(access = AccessLevel.PACKAGE)
public enum SpeedLevel implements Serializable {

    L0_RUNNING_HUMAN(0),
    L1_TRAIN(1),
    L2_SUB_SONIC(2), // Less than speed of sound
    L3_SUPER_SONIC(3), // Above speed of sound
    L4_MACH_9350(4); // fastest speed for superman on earth without causing damage

    /**
     * Push force equivalent to acceleration m/s² that is generated for given effort level
     * <p>
     * Pure acceleration output of effort put to move.
     * Not considering drag generated by the environment.
     */
    @Getter
    private double acceleration;
}
